stages:
  make_first_retriever:
    cmd: python src/make_retriever.py --config-name ret1_config
    deps:
    - src/config/ret1_config.yaml
    - src/make_retriever.py
    outs:
    - data/interim/first_retriever_vectorstore
    - data/interim/first_retriever_docstore.pkl
  make_second_retriever:
    cmd: python src/make_retriever.py --config-name ret2_config
    deps:
    - src/config/ret2_config.yaml
    - src/make_retriever.py
    outs:
    - data/interim/second_retriever_vectorstore
    - data/interim/second_retriever_docstore.pkl
  evaluate:
    cmd: python src/evaluate_chain.py data/raw/df.csv
    deps:
    - data/interim/first_retriever_vectorstore
    - data/interim/first_retriever_docstore.pkl
    - data/interim/second_retriever_vectorstore
    - data/interim/second_retriever_docstore.pkl
    - data/raw/df.csv
    - src/rag_chain.py
    - src/evaluate_chain.py
    params:
    - ensemble_retrievers.weights
    - rag_chain_setup.model
    - rag_chain_setup.template
    outs:
    - data/processed/metrics.json
